// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "extensionDC2025Sample",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "extensionDC2025Sample",
            targets: ["AppModule"],
            bundleIdentifier: "jp.objective-audio.extensionDC2025Sample",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .mic),
            accentColor: .presetColor(.teal),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            swiftSettings: [
                .enableExperimentalFeature("StrictConcurrency"),
                .define("SWIFT_STRICT_CONCURRENCY", .when(configuration: .debug))
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)